version: '3'
services:
  backend:
    build: ./backend
    container_name: backend_shopper
    ports: 
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=12345678
      - DB_NAME=db_shopper
      - DB_HOST=db
      - DB_PORT=3306 
    depends_on:
      - db
      
  db:
    image: mysql:8.0.21
    container_name: db_shopper
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql